### ISSUE TITLE
.travis.yml file is in the wrong directory

### ISSUE THREAD

**Issue by zachzundel** [michael13162/SBOLExplorer#12]
Sorry, my old PR had an issue. The .travis.yml file should be in the top-level of the repository.

**Comment by michael13162** [comment]
That makes a lot of sense.  I was wondering why Travis was taking so long to set things up haha

**Comment by zachzundel** [comment]
Hi, you merged the commit before it was finished building and Travis freaked out, please restart the build to get the new image up. Thanks!

**Comment by michael13162** [comment]
I think this is good now.
