### ISSUE TITLE
combobox instead of text fields in query form

### ISSUE THREAD

**Issue by michael13162** [michael13162/SBOLExplorer#2]
User this: https://github.com/ICO2S/sbolmeta/blob/master/lib/sequence-ontology.js

It's too confusing to type in the actual filters.  Should be able to select from a combo box for type and role.

**Comment by cjmyers** [comment]
var roleQuery = 'PREFIX sbol2: <http://sbols.org/v2#> SELECT DISTINCT ?object WHERE { ?tl a sbol2:ComponentDefinition .  ?tl sbol2:role ?object FILTER(STRSTARTS(str(?object),\'http://identifiers.org/so/\')) }'
